name: Build

on: [push]

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies with npm
      working-directory: ./client
      run: npm install
    - name: Build client
      working-directory: ./client
      run: npm run build
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies with npm
      working-directory: ./server
      run: npm install
    - name: Build server
      working-directory: ./server
      run: npm run build